import runpy


'''runpy.run_path('cnn_1.py')
runpy.run_path('cnn_2.py')
runpy.run_path('cnn_3.py')
runpy.run_path('cnn_4.py')
runpy.run_path('cnn_5.py')
runpy.run_path('cnn_6.py')
runpy.run_path('cnn_7.py')
runpy.run_path('cnn_8.py')
runpy.run_path('cnn.py')
runpy.run_path('cnn_10.py')
runpy.run_path('cnn_11.py')
runpy.run_path('cnn_12.py')
runpy.run_path('cnn_13.py')
runpy.run_path('cnn_14.py')'''
runpy.run_path('cnn_15.py')
runpy.run_path('cnn_16.py')
runpy.run_path('cnn_17.py')
runpy.run_path('cnn_18.py')
runpy.run_path('cnn_19.py')
runpy.run_path('cnn_20.py')
runpy.run_path('cnn_21.py')
runpy.run_path('cnn_22.py')
runpy.run_path('cnn_23.py')
runpy.run_path('cnn_24.py')
runpy.run_path('cnn_25.py')
runpy.run_path('cnn_26.py')
runpy.run_path('cnn_27.py')
runpy.run_path('cnn_28.py')
runpy.run_path('cnn_29.py')
runpy.run_path('cnn_30.py')
runpy.run_path('cnn_31.py')
